Add bash_completion for workspace + better help

diff --git a/Path/workspace b/Path/workspace
--- a/Path/workspace
+++ b/Path/workspace
@@ -1,66 +1,68 @@
 #!/bin/bash
 
 function printHelp() {
-	cat << EOF
+    cat << EOF
 
-	Usage:
-	${PROGNAME} `echoBlue apply` `echoGreen workspace`
-		Apply a workspace
+    Open and (re)position all windows of a given workspace.
 
-		$(echoGreen workspace): Name or index of the workspace (or empty to use an interactive dialog)
+    `echoGreen Usage:` ${PROGNAME} apply `echoBlue [workspace]`
 
-	${PROGNAME} `echoBlue list`
-		List all the workspaces
+        $(echoBlue workspace): Name or index of the workspace (or empty to use an interactive dialog)
 
-	${PROGNAME} `echoBlue config`
-		Open the config file
+    List all available workspaces.
+
+    `echoGreen Usage:` ${PROGNAME} list
+
+    Open workspaces configuration file ($CONFIG)
+
+    `echoGreen Usage:` ${PROGNAME} config
 EOF
 }
 
 function declareConstants() {
-	readonly NODE_SCRIPT="$SCRIPT_LIB/workspace/workspace.js"
-	$1 CONFIG "$SCRIPT_DATA/workspaces.json"
-	return 0
+    readonly NODE_SCRIPT="$SCRIPT_LIB/workspace/workspace.js"
+    $1 CONFIG "$SCRIPT_DATA/workspaces.json"
+    return 0
 }
 
 function loadOptions() {
-	# unusedBehaviour="IGNORE"
-	getOpt "-i" interactive
-	return 0
+    # unusedBehaviour="IGNORE"
+    getOpt "-i" interactive
+    return 0
 }
 
 function apply() {
-	if [ $# -eq 0 ]; then
-		config=$(kdialog --menu "Select" `list`)
-		test -n "$config" || return
-	else
-		config="$1"
-	fi
+    if [ $# -eq 0 ]; then
+        config=$(kdialog --menu "Select" `list`)
+        test -n "$config" || return
+    else
+        config="$1"
+    fi
 
-	node "$NODE_SCRIPT" "$CONFIG" apply "$config"
+    node "$NODE_SCRIPT" "$CONFIG" apply "$config"
 }
 
 function list() {
-	node "$NODE_SCRIPT" "$CONFIG" list
+    node "$NODE_SCRIPT" "$CONFIG" list
 }
 
 function config() {
-	xdg-open "$CONFIG"
+    xdg-open "$CONFIG"
 }
 
 function run () {
-	hasMoreArgs $#
+    hasMoreArgs $#
 
-	test -f "$CONFIG" || error "Config file not found: $CONFIG"
+    test -f "$CONFIG" || error "Config file not found: $CONFIG"
 
-	local cmds=(apply list config)
-	local cmd="$1"
-	if ! arrayContains "$cmd" "${cmds[@]}"; then
-		error "Unknown command $cmd"
-	fi
+    local cmds=(apply list config)
+    local cmd="$1"
+    if ! arrayContains "$cmd" "${cmds[@]}"; then
+        error "Unknown command $cmd"
+    fi
 
-	shift
-	$cmd "$@"
+    shift
+    $cmd "$@"
 }
 
 source "$SCRIPT_LIB/scriptStarter"
